# Generated by Django 6.0.1 on 2026-02-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('lost', 'Lost')], default='new', max_length=20)),
                ('subStatus', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=255)),
                ('NoOfEmployees', models.IntegerField()),
                ('Industry', models.CharField(choices=[('customer', 'Customer'), ('prospect', 'Prospect'), ('competitor', 'Competitor'), ('vendor', 'Vendor'), ('supplier', 'Supplier'), ('reseller', 'Reseller'), ('consultant', 'Consultant'), ('investor', 'Investor'), ('partner', 'Partner'), ('influencer', 'Influencer'), ('media', 'Media')], default='null', max_length=100)),
                ('AnnualRevenue', models.BooleanField()),
                ('WebsiteUrl', models.CharField(max_length=500)),
                ('SICCode', models.IntegerField()),
                ('Location', models.CharField(max_length=100)),
                ('Source', models.CharField(choices=[('advertisement', 'Advertisement'), ('cold call', 'Cold Call'), ('employee referral', 'Employee Referral'), ('external referral', 'External Referral'), ('partner', 'Partner'), ('public relation', 'Public Relation'), ('internal seminar', 'Internal Seminar'), ('trade show', 'Trade Show'), ('web search', 'Web Search'), ('website', 'Website'), ('campaign', 'Campaign'), ('direct incoming mail', 'Direct Incoming Mail'), ('telecall', 'Telecall'), ('visit', 'Visit')], max_length=100)),
                ('SourceCampaign', models.CharField(max_length=100)),
                ('CampaignResponse', models.CharField(max_length=100)),
                ('Account', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Opportunity', models.CharField(max_length=10)),
                ('Line1', models.CharField(max_length=100)),
                ('Line2', models.CharField(max_length=100)),
                ('Line3', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('PostCode', models.CharField(max_length=100)),
                ('TextArea', models.TextField(max_length=1000)),
                ('Owner', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=False)),
                ('CreatedBy', models.CharField(max_length=100)),
                ('CreatedOn', models.DateField(auto_now_add=True)),
                ('ModifiedBy', models.CharField(max_length=100)),
                ('ModifiedOn', models.DateField(auto_now=True)),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sales.currency', to_field='name')),
            ],
        ),
    ]
